name: 🐛 Bug Report
description: Report a bug or issue with swipe_magic
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all that apply
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I read the documentation and API reference
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a SwipeCards widget with...
        2. Swipe the card...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The card should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the card...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: dart
      placeholder: |
        import 'package:swipe_magic/swipe_magic.dart';
        
        // Your code here...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - swipe_magic version: 
        - Flutter version: 
        - Dart version: 
        - Platform (iOS/Android/Web/etc): 
        - Device/Simulator: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please provide any relevant error logs or stack traces
      render: shell
      placeholder: Paste your error logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here